# C3 Theorem Prover - Apache v2.0 - Copyright 2017 - rkx1209
CC 			=		gcc
CXX			=		g++
CP			=		cp
MAKE		=		make
UNAME		=		$(shell uname)
C3			=		c3
INCLUDE =		include
DEBUG		=		y
CFLAGS	=		-I$(INCLUDE)
CFLAGS-y= 	-g $(CFLAGS)
LDFLAGS	=		-lfl
SHELL :=		/bin/bash
INFO    =   @: echo ' '
ifeq ($(UNAME),Linux)
	INSTALL = /usr/bin/
else ifeq ($(UNAME),Darwin)
	INSTALL = /usr/local/bin
endif
