#!/bin/bash
# C3 random CNF testing
# Apache v2.0 - Copyright 2017 - rkx1209

[ -e test_template.sh ] && . ./test_template.sh

gen_cnf() {
  VALNUM=$1
  CNFNUM=$2
  CNFFILE=$3
  INPUT="c Generated by random test scripting
p cnf ${VALNUM} ${CNFNUM}
"
  for i in `seq 1 $CNFNUM`; do
    DISJNUM=$(($RANDOM % $VALNUM + 1))
    #echo "DISJNUM=${DISJNUM}"
    for j in `seq 1 $DISJNUM`; do
      # random number [-$VALNUM, $VALNUM]
      LIT=$(($RANDOM % ($VALNUM * 2) + 1 - $VALNUM))
      if [ $LIT -eq 0 ]; then
        LIT=1
      fi
      #echo "LIT=${LIT}"
      INPUT="${INPUT}${LIT} "
    done
    INPUT="${INPUT}0
"
  done
  #echo "$INPUT"
  printf "%s" "${INPUT}" > ${CNFFILE}
}

cnf_rnd() {
  NAME='random cnf'
  FILE=/tmp/random.cnf
  TESTNUM=300
  for i in `seq 1 $TESTNUM`; do
    printf 'Test: %d\n' $i
    l=$i
    gen_cnf $l $((${l}+20)) $FILE
    EXPECT='Verifying.... [SUCCESS]'
    run_test
  done
}

cnf_rnd
